import { jsPDF } from 'jspdf';
import { format, parseISO } from 'date-fns';

export const exportToPDF = (session: any, clinicName: string, doctorName: string) => {
    const doc = new jsPDF();
    const { patient_name, patient_age, gender, created_at } = session.session;
    const summary = session.summary;

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // Header
    doc.setFillColor(10, 22, 40); // Deep navy background for header
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text(clinicName, margin, 25);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Dr. ${doctorName}`, pageWidth - margin - 40, 25);

    // Patient Info
    let yPos = 55;
    doc.setTextColor(30, 41, 59); // Slate 800
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Clinical Consultation Summary", margin, yPos);
    
    yPos += 15;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`Patient: `, margin, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`${patient_name} (${patient_age} yrs, ${gender || 'Unknown'})`, margin + 20, yPos);

    doc.setFont("helvetica", "bold");
    doc.text(`Date: `, pageWidth - margin - 60, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`${format(parseISO(created_at), 'MMM dd, yyyy')}`, pageWidth - margin - 45, yPos);

    yPos += 10;
    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.line(margin, yPos, pageWidth - margin, yPos);

    if (!summary) return doc.save(`${patient_name.replace(' ', '_')}_Summary.pdf`);

    // Helper for adding sections
    const addSection = (title: string, content: string | string[], isAlert: boolean = false) => {
        yPos += 15;
        if (yPos > 270) {
            doc.addPage();
            yPos = 30;
        }

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        if (isAlert) doc.setTextColor(225, 29, 72); // Rose 600
        else doc.setTextColor(15, 23, 42);
        
        doc.text(title.toUpperCase(), margin, yPos);
        yPos += 8;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(51, 65, 85); // Slate 700

        if (Array.isArray(content)) {
            content.forEach(item => {
                if (!item.trim()) return;
                const lines = doc.splitTextToSize(`• ${item}`, pageWidth - (margin * 2) - 5);
                lines.forEach((line: string) => {
                    if (yPos > 280) { doc.addPage(); yPos = 30; }
                    doc.text(line, margin + 5, yPos);
                    yPos += 7;
                });
            });
        } else {
            const lines = doc.splitTextToSize(content || 'Not provided.', pageWidth - (margin * 2));
            lines.forEach((line: string) => {
                if (yPos > 280) { doc.addPage(); yPos = 30; }
                doc.text(line, margin, yPos);
                yPos += 7;
            });
        }
    };

    addSection('Chief Complaint', summary.chief_complaint);
    addSection('History of Presenting Illness', summary.history_of_presenting_illness);
    
    let keyFindings = [];
    try { keyFindings = JSON.parse(summary.key_findings); } catch(e){}
    addSection('Key Findings from Records', keyFindings);

    let flags = [];
    try { flags = JSON.parse(summary.clinical_flags); } catch(e){}
    if (flags && flags.length > 0 && flags[0].trim() !== '') {
        addSection('Clinical Flags', flags, true);
    }

    addSection('Assessment & Plan', summary.assessment_notes);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(`Generated by AI4CARE on ${format(new Date(), 'MMM dd, yyyy HH:mm')}`, margin, 290);

    doc.save(`${patient_name.replace(' ', '_')}_Summary.pdf`);
};
